### ISSUE TITLE
Using boost most as a manual override

### ISSUE THREAD

**Issue by psyciknz** [dadge/simple_thermostat#2]
I implemented a simple_thermostat today as I was looking for a wayh of leaving my scheduling on a thermostat which I control with automations.

At different times of the day, it changes the target temp to differing values.   Then I wanted some sort of manual override....and seeing how you have profiles and accepted the boost profile I thought that might have worked.

But with the following service I set the profile:
```
service: climate.set_preset_mode
data:
  preset_mode: boost
target:
  entity_id: climate.central_heating2

```
I can see the ui change to idle - boost.   I expected it to force on the heating switch.   Is that not th ecase?
